---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}


- name: Reload postgresql because it does not seem to recognise hba yet
  command: >
    sudo service postgresql reload
  
- name: Run Django migrate
  command: >
    {{virtualenv_path}}/bin/python manage.py migrate
  args:
    chdir: "{{ application_path }}"


- name: Create Django superuser
  command: >
    echo 'from django.contrib.auth.models import User; User.objects.create_superuser("{{DJANGO_SUPERUSER}}", "{{DJANGO_SUPERUSER_EMAIL}}", "{{DJANGO_SUPERUSER_PASSWORD}}")' | {{virtualenv_path}}/bin/python manage.py shell
  args:
    chdir: "{{application_path}}"

# the above scripts are run as root. They might have caused some logs to be owned by root.
- name: Make sure logs are owned by us
  command: >
    chown {{project_user}}:{{project_user}} {{application_log_dir}} -R
  args:
    chdir: "{{application_path}}"
    



